version: "3.8"

services:
  loki:
    image: grafana/loki:2.9.5
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
      - ./loki-wal:/wal  
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.5
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - loki
      
  ollama-agent:
    image: ollama/ollama
    container_name: ollama-agent
    environment:
      - LOKI_URL=http://loki:3100
    ports:
      - "11434:11435"
    depends_on:
      - loki
    restart: unless-stopped

  ollama-agent-wrapper:
    build: ./
    environment:
      - LOKI_URL=http://loki:3100
    ports:
      - "11435:11435"
    depends_on:
      - loki
      - ollama-agent


volumes:
  loki-data:
  grafana-data:
